"""
Step 18: Fiber Algebra — the SHAPE of the collision set

NOT metric. NOT bits. NOT invariant. NOT prediction. NOT linearization.
The STRUCTURE of the solution set itself.

F(M) = {δ : SHA(M⊕δ) = SHA(M)} — the collision FIBER.

Questions:
1. Is the fiber closed under XOR? (δ₁, δ₂ ∈ F → δ₁⊕δ₂ ∈ F?)
   If yes → fiber = linear subspace → solvable in O(n³)

2. Is the fiber closed under addition? (δ₁+δ₂ mod 2^n ∈ F?)
   If yes → fiber = subgroup of Z/2^n → structured

3. Does the fiber have SYMMETRIES? (∃σ : σ(F) = F?)
   If yes → exploit symmetry for faster search

4. What's the PAIRWISE structure? (δ₁⊕δ₂ for δ₁,δ₂ ∈ F → ?)
   Distribution of pairwise XOR/ADD of fiber elements

5. Is there a GENERATING SET much smaller than |F|?
   If yes → fiber = group generated by few elements
"""

import numpy as np
from collections import Counter
from step0_exact_algebra import mini_sha, N, MASK

N_MSG = 4
N_INPUT = N * N_MSG
N_TOTAL = 1 << N_INPUT


def compute_fiber(M, R):
    """Compute the complete collision fiber for message M at R rounds."""
    a_base, e_base = mini_sha(M, R)
    fiber = set()
    for didx in range(1, N_TOTAL):
        dw = []
        tmp = didx
        for w in range(N_MSG):
            dw.append(tmp & MASK)
            tmp >>= N
        M2 = [(M[w] ^ dw[w]) for w in range(N_MSG)]
        a2, e2 = mini_sha(M2, R)
        if a2 == a_base and e2 == e_base:
            fiber.add(didx)
    return fiber


def test_xor_closure(fiber):
    """Test: is fiber closed under XOR? (δ₁ ⊕ δ₂ ∈ F for all δ₁,δ₂ ∈ F?)"""
    fiber_with_zero = fiber | {0}  # include identity
    closed = 0
    not_closed = 0
    for d1 in fiber:
        for d2 in fiber:
            if d1 >= d2:
                continue
            xor_result = d1 ^ d2
            if xor_result in fiber_with_zero:
                closed += 1
            else:
                not_closed += 1
    total = closed + not_closed
    return closed, total


def test_add_closure(fiber):
    """Test: is fiber closed under word-level addition?"""
    fiber_with_zero = fiber | {0}

    def word_add(a, b):
        result = 0
        for w in range(N_MSG):
            aw = (a >> (w*N)) & MASK
            bw = (b >> (w*N)) & MASK
            result |= ((aw + bw) & MASK) << (w*N)
        return result

    closed = 0
    not_closed = 0
    for d1 in fiber:
        for d2 in fiber:
            if d1 >= d2:
                continue
            add_result = word_add(d1, d2)
            if add_result in fiber_with_zero:
                closed += 1
            else:
                not_closed += 1
    total = closed + not_closed
    return closed, total


def pairwise_xor_structure(fiber):
    """Analyze the distribution of pairwise XOR of fiber elements."""
    xor_results = Counter()
    fiber_list = sorted(fiber)
    for i in range(len(fiber_list)):
        for j in range(i+1, len(fiber_list)):
            xor_results[fiber_list[i] ^ fiber_list[j]] += 1

    # How many pairwise XORs land IN the fiber?
    in_fiber = sum(c for val, c in xor_results.items() if val in fiber or val == 0)
    total = sum(xor_results.values())

    # How many UNIQUE XOR results?
    n_unique = len(xor_results)

    return in_fiber, total, n_unique, xor_results


def find_generators(fiber):
    """
    Try to find a small generating set for the fiber under XOR.
    If the fiber is a linear subspace, it has a basis of size log₂(|F|).
    """
    fiber_list = sorted(fiber)
    # Greedy: start with first element, add elements that expand the span
    generators = []
    span = {0}

    for elem in fiber_list:
        if elem not in span:
            generators.append(elem)
            # Expand span
            new_span = set(span)
            for s in span:
                new_span.add(s ^ elem)
            span = new_span

            if len(span) > len(fiber) + 1:
                break

    return generators, span


def analyze_fiber(M, R):
    """Complete fiber algebra analysis."""
    print(f"\n{'='*80}")
    print(f"FIBER ALGEBRA — R={R}, M={[hex(w) for w in M]}")
    print(f"{'='*80}")

    fiber = compute_fiber(M, R)
    print(f"  |Fiber| = {len(fiber)}")
    print(f"  Expected (random 8-bit output): {N_TOTAL // (1 << (2*N))} = {N_TOTAL // 256}")

    if len(fiber) == 0:
        print(f"  Empty fiber!")
        return

    if len(fiber) > 5000:
        print(f"  Fiber too large for pairwise analysis, sampling...")
        fiber_sample = set(sorted(fiber)[:500])
    else:
        fiber_sample = fiber

    # 1. XOR closure
    print(f"\n  TEST 1: XOR CLOSURE (δ₁⊕δ₂ ∈ F?)")
    closed_xor, total_xor = test_xor_closure(fiber_sample)
    pct_xor = closed_xor / max(total_xor, 1) * 100
    expected_xor = len(fiber) / N_TOTAL * 100  # random expectation
    print(f"    Closed pairs: {closed_xor}/{total_xor} ({pct_xor:.2f}%)")
    print(f"    Random expectation: {expected_xor:.2f}%")
    print(f"    Ratio: {pct_xor / max(expected_xor, 0.01):.2f}×")
    if pct_xor > 95:
        print(f"    ★ FIBER IS XOR-CLOSED! (linear subspace)")
    elif pct_xor > expected_xor * 3:
        print(f"    ★ Significant XOR enrichment!")

    # 2. ADD closure
    print(f"\n  TEST 2: ADDITION CLOSURE (δ₁+δ₂ mod 2^n ∈ F?)")
    closed_add, total_add = test_add_closure(fiber_sample)
    pct_add = closed_add / max(total_add, 1) * 100
    print(f"    Closed pairs: {closed_add}/{total_add} ({pct_add:.2f}%)")
    print(f"    Random expectation: {expected_xor:.2f}%")
    print(f"    Ratio: {pct_add / max(expected_xor, 0.01):.2f}×")

    # 3. XOR generators
    print(f"\n  TEST 3: XOR GENERATORS (minimal generating set)")
    generators, span = find_generators(fiber)
    fiber_with_zero = fiber | {0}
    span_in_fiber = len(span & fiber_with_zero)
    print(f"    Generators found: {len(generators)}")
    print(f"    Span size: {len(span)}")
    print(f"    |Span ∩ Fiber|: {span_in_fiber}/{len(fiber_with_zero)}")
    print(f"    Span = Fiber? {'YES ★' if span == fiber_with_zero else 'NO'}")
    if span == fiber_with_zero:
        print(f"    ★ FIBER = GF(2)-SUBSPACE of dimension {len(generators)}!")
        print(f"    ★ Birthday cost: 2^{N} = {1<<N}")
        print(f"    ★ Subspace cost: JUST SOLVE LINEAR SYSTEM → O(n³)")

    # 4. Pairwise structure
    print(f"\n  TEST 4: PAIRWISE XOR DISTRIBUTION")
    in_fiber, total_pw, n_unique, xor_dist = pairwise_xor_structure(fiber_sample)
    print(f"    Pairwise XORs landing in fiber: {in_fiber}/{total_pw} ({in_fiber/max(total_pw,1)*100:.2f}%)")
    print(f"    Unique XOR results: {n_unique}")
    print(f"    Max frequency: {max(xor_dist.values()) if xor_dist else 0}")

    # 5. Hamming weight distribution
    print(f"\n  TEST 5: HAMMING WEIGHT OF FIBER ELEMENTS")
    hws = [bin(d).count('1') for d in fiber]
    hw_dist = Counter(hws)
    print(f"    Mean HW: {np.mean(hws):.1f} (random: {N_INPUT/2})")
    print(f"    Std HW: {np.std(hws):.1f}")
    print(f"    Distribution: {dict(sorted(hw_dist.items()))}")

    return fiber


def main():
    import random
    rng = random.Random(42)
    M = [rng.randint(0, MASK) for _ in range(N_MSG)]

    for R in [3, 4, 6, 8]:
        analyze_fiber(M, R)


if __name__ == "__main__":
    main()
