#!/usr/bin/env python3
"""
SCF Задача A, Этап 1: Carleman матрица одного раунда SHA-256.

SHA round (XOR-SHA, без carry):
  T1 = h ⊕ Σ1(e) ⊕ Ch(e,f,g) ⊕ K ⊕ W
  T2 = Σ0(a) ⊕ Maj(a,b,c)
  a_new = T1 ⊕ T2
  e_new = d ⊕ T1
  (остальные — сдвиги)

Нелинейности: Ch(e,f,g)[i] = e[i]f[i] ⊕ e[i]g[i] ⊕ g[i]
              Maj(a,b,c)[i] = a[i]b[i] ⊕ a[i]c[i] ⊕ b[i]c[i]

Carleman lift: вектор x = (state_bits, monomials)
  state_bits: 256 бит (a,b,c,d,e,f,g,h по 32)
  monomials: e[i]·f[i], e[i]·g[i], a[i]·b[i], a[i]·c[i], b[i]·c[i] per bit
  = 5 × 32 = 160 мономов на раунд

Начнём с n=4 бита для проверки, затем n=8, n=32.
"""
import os, sys

def bit(x, i):
    return (x >> i) & 1

def rotr_n(x, r, n):
    """Rotate right by r positions in n-bit word."""
    return ((x >> r) | (x << (n - r))) & ((1 << n) - 1)

# ============================================================
# Mini-SHA: n-bit version for Carleman construction
# ============================================================
class MiniSHA:
    """n-bit toy SHA for Carleman analysis."""

    def __init__(self, n=4):
        self.n = n
        self.mask = (1 << n) - 1
        # Rotation amounts scaled to n bits
        # Sig0: rotr(2,13,22) → rotr(n//16, n//3, n//2) approximately
        self.sig0_rots = [max(1, n//8), max(2, n//3), n//2]
        self.sig1_rots = [max(1, n//5), max(2, n//3), max(3, 3*n//4)]

    def Sig0(self, x):
        n = self.n
        return rotr_n(x, self.sig0_rots[0], n) ^ rotr_n(x, self.sig0_rots[1], n) ^ rotr_n(x, self.sig0_rots[2], n)

    def Sig1(self, x):
        n = self.n
        return rotr_n(x, self.sig1_rots[0], n) ^ rotr_n(x, self.sig1_rots[1], n) ^ rotr_n(x, self.sig1_rots[2], n)

    def Ch(self, e, f, g):
        return (e & f) ^ (~e & g) & self.mask

    def Maj(self, a, b, c):
        return (a & b) ^ (a & c) ^ (b & c)

    def xor_round(self, state, W, K=0):
        """One XOR-round (no carry)."""
        a,b,c,d,e,f,g,h = state
        T1 = h ^ self.Sig1(e) ^ self.Ch(e,f,g) ^ K ^ W
        T2 = self.Sig0(a) ^ self.Maj(a,b,c)
        return [T1^T2, a, b, c, d^T1, e, f, g]

    def state_to_bits(self, state):
        """State (8 words) → list of bits."""
        bits = []
        for w in state:
            for i in range(self.n):
                bits.append(bit(w, i))
        return bits

    def bits_to_state(self, bits):
        state = []
        for r in range(8):
            val = 0
            for i in range(self.n):
                val |= bits[r * self.n + i] << i
            state.append(val)
        return state


# ============================================================
# Build Carleman matrix for one round
# ============================================================
def build_carleman_one_round(n=4):
    """
    Build the Carleman matrix for one XOR-SHA round.

    The lifted state vector is:
      [linear_bits | quadratic_monomials]

    Linear bits: 8n (state) + n (W) = 9n
    Quadratic monomials from Ch and Maj: 5n per round
      Ch: e[i]f[i], e[i]g[i]  (2n monomials)
      Maj: a[i]b[i], a[i]c[i], b[i]c[i]  (3n monomials)

    But in Carleman, we also need monomials generated by composition.
    For ONE round: only the direct monomials matter.

    Method: evaluate the round function on all basis vectors
    to build the linear part, then on pairs to build quadratic.
    """
    sha = MiniSHA(n)
    state_bits = 8 * n  # bits in state
    w_bits = n           # bits in W (one word)
    total_linear = state_bits  # We treat W as parameter, not variable for now

    # Enumerate all degree-1 (linear) and degree-2 (quadratic) basis elements
    # Linear: state bit i = 1, rest = 0
    # Quadratic: state bits i,j both = 1, rest = 0

    # For the Carleman approach, we compute:
    # f(x) = Ax + B·(x⊗x) where A is the linear part, B is the quadratic part

    # Method: numerical differentiation over GF(2)
    # f(e_i) ⊕ f(0) = column i of A (modulo constant)
    # f(e_i ⊕ e_j) ⊕ f(e_i) ⊕ f(e_j) ⊕ f(0) = column (i,j) of B

    # Fix W = 0, K = 0 for now
    W_val = 0
    K_val = 0

    # f(0)
    zero_state = [0] * 8
    f_zero = sha.state_to_bits(sha.xor_round(zero_state, W_val, K_val))

    # Linear part: A[output_bit][input_bit]
    A = [[0] * total_linear for _ in range(total_linear)]

    for inp_bit in range(total_linear):
        # Create state with only bit inp_bit set
        test_bits = [0] * total_linear
        test_bits[inp_bit] = 1
        test_state = sha.bits_to_state(test_bits)

        f_ei = sha.state_to_bits(sha.xor_round(test_state, W_val, K_val))

        for out_bit in range(total_linear):
            A[out_bit][inp_bit] = f_ei[out_bit] ^ f_zero[out_bit]

    # Quadratic part: enumerate all pairs
    # B[output_bit][(i,j)] = f(e_i+e_j) + f(e_i) + f(e_j) + f(0)
    monomial_pairs = []
    for i in range(total_linear):
        for j in range(i+1, total_linear):
            monomial_pairs.append((i, j))

    n_monomials = len(monomial_pairs)

    # Precompute f(e_i) for all i
    f_single = []
    for inp_bit in range(total_linear):
        test_bits = [0] * total_linear
        test_bits[inp_bit] = 1
        test_state = sha.bits_to_state(test_bits)
        f_single.append(sha.state_to_bits(sha.xor_round(test_state, W_val, K_val)))

    B = [[0] * n_monomials for _ in range(total_linear)]
    nonzero_monomials = set()

    for idx, (i, j) in enumerate(monomial_pairs):
        # f(e_i + e_j)
        test_bits = [0] * total_linear
        test_bits[i] = 1
        test_bits[j] = 1
        test_state = sha.bits_to_state(test_bits)
        f_ij = sha.state_to_bits(sha.xor_round(test_state, W_val, K_val))

        for out_bit in range(total_linear):
            val = f_ij[out_bit] ^ f_single[i][out_bit] ^ f_single[j][out_bit] ^ f_zero[out_bit]
            B[out_bit][idx] = val
            if val:
                nonzero_monomials.add(idx)

    return A, B, monomial_pairs, nonzero_monomials, total_linear


# ============================================================
# Analysis
# ============================================================
def analyze_carleman(n):
    print(f"\n{'='*60}")
    print(f"CARLEMAN ANALYSIS: n={n} bits")
    print(f"{'='*60}")

    A, B, pairs, nonzero, dim = build_carleman_one_round(n)
    total_pairs = len(pairs)
    n_nonzero = len(nonzero)

    print(f"  State dimension: {dim} bits")
    print(f"  Total quadratic monomials: {total_pairs}")
    print(f"  Nonzero monomials: {n_nonzero}")
    print(f"  Carleman dimension: {dim + n_nonzero}")
    print(f"  Compression: {total_pairs} → {n_nonzero} ({n_nonzero/total_pairs*100:.1f}%)")

    # Rank of A (linear part)
    def gf2_rank(mat):
        m = [list(r) for r in mat]
        nr, nc = len(m), len(m[0]) if m else 0
        rank = 0
        for col in range(nc):
            pv = -1
            for r in range(rank, nr):
                if m[r][col]: pv = r; break
            if pv == -1: continue
            m[rank], m[pv] = m[pv], m[rank]
            for r in range(nr):
                if r != rank and m[r][col]:
                    for c in range(nc): m[r][c] ^= m[rank][c]
            rank += 1
        return rank

    rank_A = gf2_rank(A)
    print(f"\n  Rank of linear part A: {rank_A}/{dim}")

    # Rank of [A|B_nonzero] (full Carleman matrix)
    B_nonzero = []
    nonzero_list = sorted(nonzero)
    for row in range(dim):
        new_row = list(A[row]) + [B[row][idx] for idx in nonzero_list]
        B_nonzero.append(new_row)

    rank_full = gf2_rank(B_nonzero)
    carleman_dim = dim + n_nonzero
    print(f"  Rank of Carleman [A|B]: {rank_full}/{carleman_dim}")

    # Which monomials are nonzero? Classify them
    ch_monomials = 0
    maj_monomials = 0
    cross_monomials = 0

    for idx in nonzero_list:
        i, j = pairs[idx]
        # i,j are bit indices in state. Registers:
        # a: 0..n-1, b: n..2n-1, c: 2n..3n-1, d: 3n..4n-1
        # e: 4n..5n-1, f: 5n..6n-1, g: 6n..7n-1, h: 7n..8n-1
        reg_i = i // n
        reg_j = j // n
        bit_i = i % n
        bit_j = j % n

        if bit_i == bit_j:
            if {reg_i, reg_j} <= {4, 5, 6}:  # e,f,g
                ch_monomials += 1
            elif {reg_i, reg_j} <= {0, 1, 2}:  # a,b,c
                maj_monomials += 1
            else:
                cross_monomials += 1
        else:
            cross_monomials += 1

    print(f"\n  Monomial classification:")
    print(f"    Ch-type (e*f, e*g): {ch_monomials}")
    print(f"    Maj-type (a*b, a*c, b*c): {maj_monomials}")
    print(f"    Cross/other: {cross_monomials}")

    # Verify: run SHA on random inputs, check Carleman prediction
    if n <= 8:
        sha = MiniSHA(n)
        correct = 0
        total = 0
        for trial in range(min(100, 1 << (2*n))):
            state = [int.from_bytes(os.urandom(1),'big') & ((1<<n)-1) for _ in range(8)]
            actual = sha.state_to_bits(sha.xor_round(state, 0, 0))

            # Carleman prediction
            x = sha.state_to_bits(state)
            # Linear part
            pred = list(f_zero_bits) if 'f_zero_bits' in dir() else [0]*dim
            # Actually compute: pred = f(0) + A·x + B·(x⊗x)
            f0 = sha.state_to_bits(sha.xor_round([0]*8, 0, 0))
            pred = list(f0)
            for out_b in range(dim):
                for in_b in range(dim):
                    pred[out_b] ^= A[out_b][in_b] & x[in_b]
                for idx in nonzero_list:
                    i, j = pairs[idx]
                    pred[out_b] ^= B[out_b][idx] & x[i] & x[j]

            match = (pred == actual)
            if match:
                correct += 1
            total += 1

        print(f"\n  Verification: {correct}/{total} exact matches")
        if correct == total:
            print(f"  ✓ Carleman decomposition is EXACT for one round!")
        else:
            print(f"  ✗ Higher-order terms needed ({total-correct} mismatches)")

    return dim, n_nonzero, rank_A, rank_full


if __name__ == '__main__':
    print("="*60)
    print("SCF: CARLEMAN MATRIX CONSTRUCTION")
    print("  Build exact Carleman lift for one XOR-SHA round")
    print("="*60)

    results = {}
    for n in [4, 6, 8]:
        dim, n_mono, rA, rF = analyze_carleman(n)
        results[n] = (dim, n_mono, rA, rF)

    print("\n" + "="*60)
    print("SCALING SUMMARY")
    print("="*60)
    print(f"  {'n':>3} | {'state':>6} {'mono':>6} {'carleman':>9} | {'rank_A':>7} {'rank_full':>10} | {'compression':>12}")
    print("  " + "-"*65)
    for n in sorted(results):
        dim, nm, rA, rF = results[n]
        total_possible = dim*(dim-1)//2
        print(f"  {n:3d} | {dim:6d} {nm:6d} {dim+nm:9d} | {rA:7d} {rF:10d} | {nm}/{total_possible} = {nm/total_possible*100:.1f}%")

    # Extrapolate to n=32
    print(f"\n  Extrapolation to n=32 (real SHA-256):")
    dim32 = 8*32  # = 256
    # From our PART 1: 160 monomials per round, 8224 total over 64 rounds
    # But for ONE round: 160 nonzero monomials expected
    # Total possible: C(256,2) = 32640
    print(f"    State: {dim32} bits")
    print(f"    Expected nonzero monomials (1 round): ~160")
    print(f"    Total possible: {dim32*(dim32-1)//2}")
    print(f"    Carleman dim (1 round): ~{dim32 + 160}")
    print(f"    Over 64 rounds: ~{dim32 + 8224} = 8480")
    print(f"    vs full quadratic space: {dim32 + dim32*(dim32-1)//2} = {dim32+dim32*(dim32-1)//2}")
    print(f"    Compression: {8224}/{dim32*(dim32-1)//2} = {8224/(dim32*(dim32-1)//2)*100:.1f}%")
